import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'


export default function Home() {
  return (
 
      <>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
        
       <div className=''>
        <div className='grid grid-cols-1'>
          <div className='w-12/12'>
            <h2 className='justify-left mt-10 lg:ml-72 text-xl font-semibold'>
              Recent Articles
            </h2>
          </div>
       </div>
       
      
      </div>
    </>
  )
}
